import { NextResponse } from "next/server";

export async function GET() {
  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
   <url>
      <loc>https://assignmentinneed.co.uk/</loc>
      <priority>1</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/marketing-assignment-writing-help</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/business-assignment-writing-help</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/management-assignment-writing-help</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/entrepreneurship-assignment-help-uk</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/finance-assignment-writing-help</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/accounting-assignment-writing-help</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/economic-assignment-writing-help</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/statistics-assignment-writing-help</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/law-assignment-writing-help</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/engineering-assignment-writing-help</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/computer-science-assignment-writing-help</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/machine-learning-assignment-help-uk</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/artificial-intelligence-assignment-help-uk</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/nursing-assignment-writing-help</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/biology-assignment-help-uk</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/chemistry-assignment-writing-help</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/physics-assignment-writing-help</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/math-assignment-help</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/humanities-assignment-help-uk</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/psychology-assignment-help-uk</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/sociology-assignment-writing-help</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/geography-assignment-writing-help</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/philosophy-assignment-writing-help</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/programming-assignment-writing-help</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/english-assignment-writing-help</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/linguistic-assignment-writing-help</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/dissertation-editing-and-proofreading-help-uk</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/dissertation-topic-selection-service-help-uk</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/dissertation-writing-help-services</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/dissertation-literature-review-help-uk</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/dissertation-results-help-uk</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/dissertation-findings-help-uk</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/reflective-essay-help-uk</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/descriptive-essay-help-uk</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/personal-statement-essay-help-uk</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/argumentative-essay-help-uk</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/literature-review-essay-help-uk</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/analytical-essay-help-uk</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/persuasive-essay-help-uk</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/extended-essay-help-uk</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/custom-research-paper-help-uk</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/masters-research-paper-help-uk</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/phd-research-paper-help-uk</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/homework-writing-help-services</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/thesis-writing-help</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/summary-writing-help</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/personal-statement-writing-help</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/coursework-writing-help</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/term-paper-writing-help</loc>
      <priority>0.9</priority>
   </url>
</urlset>`;

  return new NextResponse(xml, {
    headers: {
      "Content-Type": "application/xml; charset=utf-8",
    },
  });
}
