import { NextResponse } from "next/server";

export async function GET() {
  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
   <url>
      <loc>https://assignmentinneed.co.uk/writers</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/emily-roberts</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/ruby-gray</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/peter-lewis</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/julian-wells</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/catherine-brooks</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/james-cooper</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/harry-king</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/sophie-brown</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/elizabeth-harris</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/natalie-green</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/casey-parker</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/laura-baker</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/ethan-page</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/miles-turner</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/alex-carter</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/william-evans</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/liam-carter</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/george-harris</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/amy-frost</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/hannah-flynn</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/avery-hudson</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/sam-birch</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/leo-hayes</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/helen-scott</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/levi-adams</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/helen-richards</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/sam-harper</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/adam-brook</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/sophia-white</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/owen-grant</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/isabella-morris</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/lucy-taylor</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/daniel-evans</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/sara-mills</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/finley-ward</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/victor-harris</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/jamie-ellis</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/samuel-wright</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/edward-roberts</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/daniel-foster</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/grace-wood</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/abigail-clarke</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/taylor-morgan</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/ryan-nash</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/derek-adams</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/thomas-reid</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/sophia-adams</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/lucas-lane</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/simon-evans</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/blake-rivers</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/mia-ford</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/ben-ward</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/jason-fielding</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/tyler-vaughn</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/emma-clarke</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/david-kingston</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/simon-hughes</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/erick-benett</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/richard-grant</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/julia-adams</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/ryan-blair</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/john-smith</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/joseph-lewis</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/etios-palmer</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/chloe-finch</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/kate-williams</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/richard-harrison</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/davis-allen</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/jonathan-walker</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/noah-warner</loc>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/writers/laura-evans</loc>
      <priority>0.8</priority>
   </url>
</urlset>`;

  return new NextResponse(xml, {
    headers: {
      "Content-Type": "application/xml; charset=utf-8",
    },
  });
}
