import { NextResponse } from "next/server";

export async function GET() {
  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/human-resource-management/how-employee-engagement-of-tesco-has-an-impact-on-the-companys-business-performance-advantages-limitations-and-recommendations-essay</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Nursing/ethical-problems-in-nursing-case-study-and-student-awareness</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/essay-understanding-audit-risks-and-internal-controls-in-the-wine-industry-a-case-study-of-trunkey-creek</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/philosophy/ancient-philosophy-and-its-current-influence-in-modern-thought</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/relative-fiscal-performance-analysis-marks-spencer-vs-next-plc</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/English</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/History</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/human-resource-management/swot-analysis-for-the-organic-food-industry-an-in-depth-essay-on-market-trends-and-challenges</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/ethical-dilemmas-in-accounting-over-prediction-vs-over-stating-of-financials-an-in-depth-essay</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/reflective-essay-on-managing-room-divisions-in-the-hotel-industry</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/contract-of-service-vs-contract-for-services-differences-in-defining-uk-employment-law</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/English/literary-analysis-understanding-themes-characters-and-symbols-in-assignments</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/philosophy/the-basic-problems-of-existence-a-step-to-existentialism</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/History/top-7-common-mistakes-in-history-assignments-and-how-to-avoid-them</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/English/exploring-british-identity-in-post-brexit-literature</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/strategies-for-writing-an-effective-operational-essay</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/marketing/marketing-strategy-analysis-of-tesco-plc-in-the-uk-retail-sector</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Linguistic/syntax-and-semantics-the-central-points-of-linguistic-analysis</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/an-interactive-essay-on-conceptual-design-understanding-distributed-messaging-systems-for-tech-geeks</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/analysis-of-financial-ratios-for-dominos-pizza-and-comparison-with-starbucks</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/human-resource-management/key-factors-shaping-chinas-nhrd-policy-and-how-they-impact-ld-strategies-for-young-professionals</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Linguistic/exploring-the-evolution-of-language-across-cultures</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/assaying-gsk-plcs-profitability-zero-grounded-budgeting-balanced-scorecard-and-investment-strategies</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/worksheet-for-evaluating-acquisitions-and-consolidation-processes</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/History/modern-history-the-impact-of-the-industrial-revolution</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/understanding-carrying-value-of-property-plant-and-equipment-cost-model-fair-value-revaluation-and-impairment-an-in-depth-essay-with-examples-and-journal-entries</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/marketing/objectivity-and-independence-in-auditing-threats-and-safeguards</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/cost-accounting-job-costing-equivalent-units-and-allocation-of-joint-costs</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/History/world-history-key-events-of-the-20th-century</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Linguistic/language-acquisition-understanding-first-and-second-language-learning</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Physics/the-role-of-quantum-physics-in-modern-technology</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/classical-arguments-for-the-existence-of-god-an-analytical-essay</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/examine-how-budgeting-influences-managerial-performance-at-caltex-providing-insights-into-its-effectiveness-and-areas-for-strategic-improvement</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/evaluating-and-identifying-threats-to-auditor-independence</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/fair-value-accounting-essay-benefits-and-drawbacks-explained-to-young-professionals-concerning-the-three-tier-system</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/smart-business-decisions-essay-a-critical-guide-to-analyzing-strategies-for-success</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/human-resource-management/the-role-of-self-awareness-in-leadership-an-essay-on-emotional-intelligence-for-young-professionals</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/accounting-share-capital-tax-asset-revaluation</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Economic/understanding-economics-supply-demand-and-market-equilibrium-for-homework</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Nursing/a-review-of-mental-health-policies-in-the-nhs-a-uk-perspective</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/essay-on-financial-accounting-in-the-liquidation-of-companies-preface</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/sociology/social-stratification-and-its-impact-on-communities-deep-insight</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/westpacs-evolution-and-growth-strategic-perceptivity-analysis-and-practices</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/introducing-project-portfolio-management-in-coca-cola-situational-context-opportunities-and-insights</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/taxi-style-essay-sun-wukong-and-the-new-transformation-at-melbourne-airport-travel-for-young-professionals</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/English/mastering-english-for-academic-communication</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/crucial-events-impacting-the-inspection-of-bhp-group-an-analysis</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/the-future-of-sydneys-growth-key-theories-and-ideas-influencing-the-developing-city</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/exploring-manufacturing-overheads-a-comparative-analysis-of-conventional-and-activity-based-costing</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/abc-analysis-of-inventory-management</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/factors-impact-and-results-in-organizational-performance</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/audit-planning-report-how-to-structure-an-effective-strategy-for-fallow-enterprises-asa-300-essay-guide</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/essay-management-accounting-vs-financial-accounting-key-changes-and-the-impact-of-the-balanced-scorecard-on-decision-making</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/assessing-the-costs-of-products-and-services</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/analysis-of-the-strengths-and-weaknesses-of-coca-cola-amati-and-pacific-beverage-companies</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/sociology</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/sociology/urban-sociology-challenges-of-modern-cities</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/comparative-analysis-of-portfolio-construction-and-returns-apple-inc-vs-microsoft-stocks</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/essay-comparative-analysis-of-financial-accounting-services-dbm-vs-azure-group</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/leadership-in-business-important-factors-and-traits-for-leadership-success-an-essay</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Linguistic</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/audit-risk-identification-a-comprehensive-overview</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/contemporary-issues-in-accounting-management-cost-environmental-corporate-and-social-accounting-analysis</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Economic</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/essay-on-how-in-person-crowdfunding-events-shape-the-future-of-event-and-entertainment-management</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Business/social-media-marketing-a-game-changer-for-small-businesses</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/assaying-pitfalls-and-fiscal-performance-in-auditing-and-account</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/a-critical-evaluation-of-orora-limiteds-adherence-to-australian-accounting-norms-in-general-purpose-financial-reporting</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/understanding-assessed-income-in-australia</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Nursing</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/sociology/understanding-cultural-norms-through-ethnographic-studies</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Business</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/analysis-of-medibanks-annual-report-and-client-dissatisfaction</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Math</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/essay-on-investment-and-fiscal-analysis</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/human-resource-management/the-impact-of-fall-prevention-strategies-on-elderly-diabetic-patients-an-insightful-essay</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/overview-and-assessment-of-certificate-iv-in-finance-and-mortgage-brokerage</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/philosophy</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/lonu053-global-finance-and-accounting-an-analytical-essay</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/assessment-of-slh-groups-sustainability-reporting-and-accounting-practices</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/human-resource-management</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/ratio-analysis-financial-performance</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/analysis-of-asic-v-rich-directors-duties-and-the-operation-of-the-business-judgment-rule</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/ways-in-operation-account-for-enhanced-fiscal-decision-making</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/human-resource-management/mastering-strategic-planning-a-prensky-type-essay-on-business-growth-and-management</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/the-applicability-and-operation-of-the-social-contract-in-legitimacy-theory-within-accounting</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/operation-and-benefits-of-exertion-grounded-going-in-the-construction-industry-a-case-study-of-tbr-infra-pvt-ltd</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/essay-organizational-strategies-of-uber-an-exploration-of-actionable-insights</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/human-resource-management/strategic-hr-management-maximizing-your-companys-website-essay</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/valuation-of-fixed-income-securities-and-dividend-growth-stocks</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/financial-accounting-essay-classification-and-share-capital-with-taxation-and-revaluation-of-asset-for-newest-business-ventures</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/review-and-assess-certificate-iv-in-finance-and-mortgage-broking-covering-key-skills-career-advancements-and-practical-knowledge-essentials</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/analysis-of-profitability-and-liquidity-rates</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Geography/geography-climate-change-sustainability-and-ecosystem-services</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/human-resource-management/mastering-workplace-conflict-management-guide-to-effective-essay-writing</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/assessment-of-auditing-practices-and-risk-management-at-double-ink-printers-limited</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Economic/understanding-economic-theories-classical-keynesian-and-monetarism-assignment</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/marketing-inspection-for-samsung-situational-analysis-internal-strengths-and-sins-and-stp-analysis-essay</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/analysing-changing-trends-in-the-uk-grocery-sector</loc>
      <priority>0.9</priority>
   </url>
   <url>
      <loc>https://assignmentinneed.co.uk/free-samples/Account/anzs-profit-report-and-public-concerns-regarding-banking-standards</loc>
      <priority>0.9</priority>
   </url>
</urlset>`;

  return new NextResponse(xml, {
    headers: {
      "Content-Type": "application/xml; charset=utf-8",
    },
  });
}
